/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADD = 5;
  /** RegularExpression Id. */
  int SUB = 6;
  /** RegularExpression Id. */
  int DIV = 7;
  /** RegularExpression Id. */
  int MOD = 8;
  /** RegularExpression Id. */
  int MULT = 9;
  /** RegularExpression Id. */
  int LPAR = 10;
  /** RegularExpression Id. */
  int RPAR = 11;
  /** RegularExpression Id. */
  int ASSIGN = 12;
  /** RegularExpression Id. */
  int EXP_DEL = 13;
  /** RegularExpression Id. */
  int DEF = 14;
  /** RegularExpression Id. */
  int IN = 15;
  /** RegularExpression Id. */
  int END = 16;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 17;
  /** RegularExpression Id. */
  int IDENTIFIER = 18;
  /** RegularExpression Id. */
  int LETTER = 19;
  /** RegularExpression Id. */
  int DIGIT = 20;
   int NEW=21;
   int GREATER=22;
   int GREATEROREQ=23;
   int LOWER=24;
   int LOWEROREQ=25;
   int AND=26;
   int OR=27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"%\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\";\"",
    "\"def\"",
    "\"in\"",
    "\"end\"",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
          "\"new\"",
          "\">\"",
          "\">=\"",
          "\"<\"",
          "\"<=\"",
          "\"&&\"",
          "\"||\"",
    "\",\"",
  };

}
