/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DEF = 5;
  /** RegularExpression Id. */
  int IN = 6;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int THN = 8;
  /** RegularExpression Id. */
  int ELS = 9;
  /** RegularExpression Id. */
  int WHL = 10;
  /** RegularExpression Id. */
  int DO = 11;
  /** RegularExpression Id. */
  int NEW = 12;
  /** RegularExpression Id. */
  int END = 13;
  /** RegularExpression Id. */
  int INT = 14;
  /** RegularExpression Id. */
  int BOL = 15;
  /** RegularExpression Id. */
  int REF = 16;
  /** RegularExpression Id. */
  int PRT = 17;
  /** RegularExpression Id. */
  int PRL = 18;
  /** RegularExpression Id. */
  int MO_POS = 19;
  /** RegularExpression Id. */
  int MO_NEG = 20;
  /** RegularExpression Id. */
  int MO_PRO = 21;
  /** RegularExpression Id. */
  int MO_DIV = 22;
  /** RegularExpression Id. */
  int MO_MOD = 23;
  /** RegularExpression Id. */
  int DEFINE = 24;
  /** RegularExpression Id. */
  int ASSIGN = 25;
  /** RegularExpression Id. */
  int DEREF = 26;
  /** RegularExpression Id. */
  int CMP_EQ = 27;
  /** RegularExpression Id. */
  int CMP_LT = 28;
  /** RegularExpression Id. */
  int CMP_LE = 29;
  /** RegularExpression Id. */
  int CMP_GT = 30;
  /** RegularExpression Id. */
  int CMP_GE = 31;
  /** RegularExpression Id. */
  int LO_OR = 32;
  /** RegularExpression Id. */
  int LO_AND = 33;
  /** RegularExpression Id. */
  int LO_NOT = 34;
  /** RegularExpression Id. */
  int TERM = 35;
  /** RegularExpression Id. */
  int DLMT = 36;
  /** RegularExpression Id. */
  int COM = 37;
  /** RegularExpression Id. */
  int L_PAR = 38;
  /** RegularExpression Id. */
  int R_PAR = 39;
  /** RegularExpression Id. */
  int COLN = 40;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 41;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 42;
  /** RegularExpression Id. */
  int BOOLEAN_LITERAL = 43;
  /** RegularExpression Id. */
  int IDENTIFIER = 44;
  /** RegularExpression Id. */
  int LETTER = 45;
  /** RegularExpression Id. */
  int DECIMAL = 46;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"def\"",
    "\"in\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"new\"",
    "\"end\"",
    "\"int\"",
    "\"bool\"",
    "\"ref\"",
    "\"print\"",
    "\"println\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "\":=\"",
    "\"!\"",
    "\"==\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"||\"",
    "\"&&\"",
    "\"~\"",
    "\";;\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<BOOLEAN_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DECIMAL>",
  };

}
